version: '3.9'

services:
  liquibase:
    build:
      context: ../
      dockerfile: Dockerfile
    env_file:
      - ../.env
    environment:
      LIQUIBASE_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=require
      LIQUIBASE_USERNAME: ${POSTGRES_USER}
      LIQUIBASE_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ../changelog.yaml:/changelog.yaml:ro
      - ../migrations:/migrations:ro
      - ../liquibase.properties:/liquibase.properties:ro
    command: update
    networks:
      - trainingLog-net

networks:
  trainingLog-net:
    driver: bridge
